### ISSUE TITLE
harfbuzz 1.2 breaks display of some accented characters with font cantarell

### ISSUE THREAD

**Issue by rhertzog** [behdad/harfbuzz#246] opened 2016-04-26 15:11 UTC
Moving from https://bugs.freedesktop.org/show_bug.cgi?id=95148 (BTW you should really update https://www.freedesktop.org/wiki/Software/HarfBuzz/ if you want new bug reports here)

With version 1.2.6 of harfbuzz and fonts-cantarell 0.0.21 I get incorrectly formatted accents in labels in GTK-3 apps at least.

A word like "Fenêtres" is badly displayed with the "t" being displayed on top of the "ê". The "^" accent is a dead-letter so it must be combined with the next letter when input on the keyboard, but once combined it should obviously no longer have this attribute...

Example here:
![bad-display](https://cloud.githubusercontent.com/assets/1013915/14823113/a67a0114-0bd1-11e6-8211-0dc0ff2a95dc.png)

A german user also saw a similar problems with "ü".

I don't know if this is a bug in harfbuzz or in fonts-cantarell (as I don't have the problem with other fonts, I tried with Linux Libertine which is also an OpenType font and it was fine).

This bug has also been reported to Debian here: https://bugs.debian.org/822682

**Comment by adrientetar** [comment] 2016-04-26 16:25
This seems a duplicate of #228 which is a font issue.

**Comment by khaledhosny** [comment] 2016-04-26 17:57
What @adrientetar, it is a bug in the font and a fixed version have been released already.

**Closed by khaledhosny** 2016-04-26 17:57 UTC
Labels: duplicate

**Comment by behdad** [comment] 2016-04-26 18:53
> BTW you should really update https://www.freedesktop.org/wiki/Software/HarfBuzz/ if you want new bug reports here)

We never decided to move, it's just that people started filing here.  I think it's about time to move officially...

**Comment by behdad** [comment] 2016-04-26 18:54
If there's a one particular version of the font that is in wide circulation, I can blacklist its GDEF table.  In that case, I need the font file.

**Comment by adrientetar** [comment] 2016-04-26 19:01
I think gnome-cantarell releases regularly...
