### ISSUE TITLE
consonant conjugate with halant u+0ccd

### ISSUE THREAD

**Issue by MayuraVerma** [behdad/harfbuzz#547] opened 2017-10-01 23:16 UTC
Please open the below link in mac OS high Sierra in Chrome and Safari

http://kannadafont.blogspot.com/2017/10/case9-consonant-conjugate-with-halant.html

Both Kannada Sangam MN and Kannada MN fail to render text correctly in Chrome. But it works just fine in Safari

In Chrome
![chrome](https://user-images.githubusercontent.com/14062593/31060180-a270e17e-a6d4-11e7-91d9-659aeb6aa8c6.png)

In Safari
![safari](https://user-images.githubusercontent.com/14062593/31060182-afc0e0f4-a6d4-11e7-872f-81030a394527.png)

Please review.

**Comment by behdad** [comment] 2017-10-03 11:59
Duplicate of https://github.com/behdad/harfbuzz/issues/531

**Closed by behdad** 2017-10-03 11:59 UTC
