### ISSUE TITLE
Change to mark-zeroing in HB 1.2.0 has regressed some fonts due to bad GDEF tables

### ISSUE THREAD

**Issue by jfkthame** [behdad/harfbuzz#264] opened 2016-06-14 15:53 UTC
See mozilla bugs:
  https://bugzilla.mozilla.org/show_bug.cgi?id=1279925
  https://bugzilla.mozilla.org/show_bug.cgi?id=1279693

I confirmed that reverting b3582a8ee8 (and the followup eaadcbbc53) fixes the problem with IPA characters in Tahoma, using the font shipped with Windows 8.1. (This seems to be a long-standing font bug, given that we also have an old report at https://bugzilla.mozilla.org/show_bug.cgi?id=653993.)

**Comment by behdad** [comment] 2016-06-14 16:12
Ack.  Sorry for the late response; been up in the air.  Shall we blacklist some more fonts?

**Comment by jfkthame** [comment] 2016-06-14 16:40
n/p, I'm also away from my usual desk this week.

I'm not sure if the individual table-based blacklist is the best approach here, given that this seems to be a longstanding bug that has existed in numerous releases of Tahoma/TahomaBold; it'll get pretty ugly to enumerate them one by one. I have at least 8 problematic fonts on hand already, without going in search of versions from Windows 7 or from older/newer MacOSX releases than what I'm currently running.

How much would we lose if we reverted to zeroing by Unicode for Latin? (And for Tibetan, per bug 1279693.)

**Comment by behdad** [comment] 2016-07-21 08:16
I merged this, but keeping issue open to discuss further changes.

**Comment by dequis** [comment] 2016-08-19 10:58
Oh hi there, spent a couple of hours doing regression tests between firefox 46 and 47 and then between harfbuzz 1.1.3 and 1.2.0* and I just noticed this is my issue!

Segoe UI and Noto Sans seem to turn the backtick character into a combining character after b3582a8ee82942a931130a83b2867b239f8ca71a. The blacklisted stuff in master doesn't help.

This happens mainly in github, most other websites don't use those fonts.

![](http://dump.dequis.org/H2mhv.gif)

*For some reason doing `make clean && make && sudo make install` while bisecting led me to wrong results, as if the binary didn't change. Took me way too long to realize `./configure` was needed too. Not the smoothest bisection.

**Comment by behdad** [comment] 2016-09-02 16:51
@jfkthame given more reports that came in, what do you think we should do here?

**Comment by jfkthame** [comment] 2016-09-02 17:12
Remind me, if we switch the generic shaper back to zeroing by Unicode instead of GDEF, what will that break? Anything?

**Comment by behdad** [comment] 2016-09-02 17:37
> Remind me, if we switch the generic shaper back to zeroing by Unicode instead of GDEF, what will that break? Anything?

Last time it was breaking minor scripts.  So, if we change, we should change just Latin or LGC.  But I prefer to either 1. respect what font designer put into font, or 2. figure out what heuristics DirectWrite is using and possibly emulate that.

I hear DirectWrite might be skipping shaping if there's no default-on feature in the font (globally) other than liga and kern.  I'll ask for clarification.  Note that I'm NOT suggesting we skip shaping or necessarily use this heuristic to decide whether to ignore GDEF.  I just want to better understand why DirectWrite does not have the same bug.

**Comment by jfkthame** [comment] 2016-09-05 14:07
@dequis What version of Segoe UI are you using where you see this problem?

**Comment by dequis** [comment] 2016-09-05 20:26
fc-query shows `fontversion: 350618(i)(s)` ([full output](https://github.com/behdad/harfbuzz/files/455594/segoeui.txt))

It was taken from windows 8.0 or 8.1, don't remember which one i had at the time. 

```
$ md5sum segoeui.ttf
b9e9836ef247552bfd77832dfac2d8d8  segoeui.ttf
```

**Comment by jfkthame** [comment] 2016-09-06 13:38
That's Segoe UI from Win8.1, I believe. But I'm not seeing this issue with that font. Are you sure you're entering the (spacing) ASCII grave character, U+0060? Might you have a keyboard layout that's actually generating a combining grave accent, U+0300?

**Comment by dequis** [comment] 2016-09-06 19:40
Okay, my bad, infinality's variant of fontconfig must have been replacing Segoe UI (which is what github specifies in its font-family) with Noto Sans. After replacing with stock fontconfig/freetype2/cairo/etc github looks noticeably different and the issue is not present when that font is selected, it's just Noto Sans.

The character is definitely fine as it's what I use for `markdown code blocks`. Oh man it `feels` so `good` to be able to write `those` normally `again`. 

```
:D:D:D
```

**Comment by behdad** [comment] 2016-09-07 20:20
@dequis what version of Noto Sans is that?  Where did you get it from?

**Comment by dequis** [comment] 2016-09-07 20:40
Uh, yeah, about that... This is embarrassing. I had a really old package, `ttf-google-fonts-git-20130806`. I noticed this after posting my last comment and tried to rebuild a new one yesterday but got a kernel panic probably because of overheating when compressing the package. So I'll report back if it turns out that the new one fixes it and that I'm an idiot. I apologize in advance.

Current version is `fontversion: 68157(i)(s)` ([fc-query output and md5sum](https://github.com/behdad/harfbuzz/files/460283/noto.txt))

**Comment by dequis** [comment] 2016-09-07 21:09
`fontversion: 69468(i)(s)` isn't affected.

However, building a new `ttf-google-fonts-git` package didn't help, because it grabs from [the google/fonts git repo][1] which still has [the same NotoSans-Regular.ttf version][2] from three years ago, 68157, which has this issue. So, not 100% my fault! Yay!

If it matters, the exact file I had ([uploaded here][3]) was subtly different from that one, even though both have the same version and the same issue. That git repo didn't even exist back in 2013 apparently (initial commit says 2015). I don't know.

[fc-query output and md5sum of the other 68157 from the git repo, for diffing](https://github.com/behdad/harfbuzz/files/460322/noto2.txt)

[1]: https://github.com/google/fonts
[2]: https://github.com/google/fonts/blob/master/ofl/notosans/NotoSans-Regular.ttf
[3]: http://dump.dequis.org/YcNDH.ttf

**Comment by behdad** [comment] 2016-09-07 21:33
cc @davelab6

**Comment by KrasnayaPloshchad** [comment] 2016-09-27 13:32
> I just want to better understand why DirectWrite does not have the same bug.

I think making more improvements on `hb-directwrite` would help.

**Comment by ebraminio** [comment] 2016-09-27 13:39
> I think making more improvements on hb-directwrite would get help.

What improvements it needs? Perhaps I can help.

**Comment by behdad** [comment] 2017-03-02 07:02
Closing until another push comes in.

**Closed by behdad** 2017-03-02 07:02 UTC
