### ISSUE TITLE
Pick script/lang that has 'vert' table

### ISSUE THREAD

**Issue by kojiishi** [behdad/harfbuzz#95] opened 2015-03-30 12:59 UTC
There are cases where input script/lang does not match to what the font has 'vert' table in.

It'd be great if HB has either:

1. Correct script/lang as needed so that 'vert' applies, or
2. Have a method to let app know in which script/lang the font has 'vert' in.

Longer description follows.

Scripts/langsys do not work well for multi-scripts languages such as CJK, and historically, different font/engine vendors did different workaround for the problem that engines need to be tolerant to find 'vert' when processing CJK text, sometimes to support broken fonts, or sometimes because of different workaround taken.

Due to this, most implementations display correctly even when fonts have wrong or broken scripts/langsys. Safari/IE renders such pages/fonts correctly. Blink has its own workaround today, but it'd be ideal if HB does this.

**Comment by behdad** [comment] 2015-03-30 20:40
Show me the failing font first.

**Comment by kojiishi** [comment] 2015-03-31 02:26
Consider this case:

* A paragraph starting with an CJK open parenthesis, U+300C for example. Script=Common.
* A word of Script=Arabic follows, then Scrpit=hani text follows.

We need to apply 'vert' to the open parenthesis.

**Comment by behdad** [comment] 2015-04-01 19:03
The font is free to reference 'vert' feature from every script (including Arabic) if it desire to.

FWIW, I'm yet to see evidence that any system other than Chrome/Safari's shared implementation do this hack the way you are asking.

**Comment by behdad** [comment] 2015-07-23 09:34
Dupe of https://github.com/behdad/harfbuzz/issues/63

**Closed by behdad** 2015-07-23 09:34 UTC
