### ISSUE TITLE
issue rendering Kannada script?

### ISSUE THREAD

**Issue by marekjez86** [behdad/harfbuzz#260] opened 2016-06-08 04:49 UTC
Sample text: ಹುಣ್ಣಿಮೆ

The above text is rendered as

![kannada-01-regular](https://cloud.githubusercontent.com/assets/13322623/15882992/fbb4d012-2cf8-11e6-83d0-a569ec84ac74.png)

the above png was created by calling the following command
hb-view /Users/marekj/Downloads/NotoSerifKannada_20160524\ (1)/NotoSerifKannada_unhinted/NotoSerifKannada-Regular.ttf --output-format=png --text-file=specimen/kannada-01.txt --font-size=48 --language=kn > specimen/kannada-01-regular.png

textEdit on Mac renders it (allegedly correctly) as
![textedit-kannada-01](https://cloud.githubusercontent.com/assets/13322623/15883020/70008ee8-2cf9-11e6-81a3-1f529a1ec39f.jpg)

maybe I needed to provide something in --script= argument to hb-view

**Comment by marekjez86** [comment] 2016-06-08 04:57
similar rendering problem appears to be
ಪ್ರಯೋಗದಲ್ಲಿಯೂ
in the
ಯೋ fragment

**Comment by marekjez86** [comment] 2016-06-08 05:00
user provided wrong rendering (we generated in fontdiff)
<img width="168" alt="kannada_wrong" src="https://cloud.githubusercontent.com/assets/13322623/15883238/255cfa78-2cfb-11e6-8ef1-fc5d2c02ebce.png">
according to this user it should look like
<img width="256" alt="kannada_right" src="https://cloud.githubusercontent.com/assets/13322623/15883247/36f90d26-2cfb-11e6-80a8-96fb40af1295.png">

**Comment by behdad** [comment] 2016-06-08 22:01
There might be a problem with your build of harfbuzz.  Which NotoSansKannada is that?  With the one in noto-fonts repo, it works for me as expected.

**Comment by marekjez86** [comment] 2016-06-08 22:17
I'll rebuild the hb-view using the most recent harfbuzz.

It is using Serif Kannada.
see
https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSerifKannada-Regular.ttf



On Wed, Jun 8, 2016 at 3:02 PM, Behdad Esfahbod <notifications@github.com>
wrote:

> There might be a problem with your build of harfbuzz. Which
> NotoSansKannada is that? With the one in noto-fonts repo, it works for me
> as expected.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/behdad/harfbuzz/issues/260#issuecomment-224743361>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMtJf0tcFAcS_SLzapHGlYcCdRZ9TLZHks5qJzvYgaJpZM4Iwl0X>
> .
>



-- 

Marek Z Jeziorek [ 老马 ] | marekj@google.com | 312 725-6958

**Comment by behdad** [comment] 2016-06-08 22:32
Ah, Serif.  Ok, confirmed this is a HarfBuzz bug.  Will look into it soonish.

**Comment by MayuraVerma** [comment] 2016-10-19 14:52
Hello @behdad 

Any updates on this issue?

There seems to be more issue with serif #347 and #341 

Please fix them as soon as possible.

**Comment by MayuraVerma** [comment] 2016-10-26 22:15
Hello @behdad 

Please fix this issue. 
It is making Noto-Serif and many other Kannada fonts impractical.

**Comment by lianghai** [comment] 2016-12-15 11:05
Confirmed it's related to HarfBuzz's way of handling GDEF.

@MayuraVerma, @behdad: Please see my comment in https://github.com/behdad/harfbuzz/issues/347

**Comment by MayuraVerma** [comment] 2016-12-18 23:03
@lianghai thank you.

**Comment by MayuraVerma** [comment] 2017-04-03 03:46
This is now fixed in harfbuzz, I suppose. It is already reflecting correctly in chrome version 57.

**Comment by behdad** [comment] 2017-07-14 13:35
Correct.  Duplicate of https://github.com/behdad/harfbuzz/issues/347 and confirmed fixed already.

**Closed by behdad** 2017-07-14 13:35 UTC
Labels: Android, bug, Priority-High
