### ISSUE TITLE
Adding heuristic for using 'vert' even for incomplete Script/LangSys combinations

### ISSUE THREAD

**Issue by drott** [behdad/harfbuzz#117] opened 2015-07-01 09:02 UTC
Just creating this as a tracking bug after discussion in https://code.google.com/p/chromium/issues/detail?id=470884#c24 
CC @kojiishi

**Comment by behdad** [comment] 2015-07-22 16:05
Dupe of https://github.com/behdad/harfbuzz/issues/63

**Closed by behdad** 2015-07-22 16:05 UTC
