### ISSUE TITLE
Kannada text issue with ZERO WIDTH JOINER

### ISSUE THREAD

**Issue by MayuraVerma** [behdad/harfbuzz#341] opened 2016-10-10 03:23 UTC
There seems to be an issue with "ZERO WIDTH JOINER" and "\u0cb0\u0ccd" combination.
\u0cb0\u0ccd\u200d\u0c95

incorrect display in crome
![incorrect display in crome](https://cloud.githubusercontent.com/assets/14062593/19226292/ecd28c60-8e6e-11e6-8b5b-ed480a80a0a5.png)

correct display in ms word
![correct display in ms word](https://cloud.githubusercontent.com/assets/14062593/19226287/d350a7fe-8e6e-11e6-8a71-9706efa24a57.png)

Check the below text in chrome and comparing it with Microsoft word.

ರ ರ್‍ಕ    ರ್‍ಖ    ರ್‍ಗ    ರ್‍ಘ    ರ್‍ಙ    ರ್‍ಚ    ರ್‍ಛ    ರ್‍ಜ    ರ್‍ಝ

https://en.wikipedia.org/wiki/Kannada_alphabet

**Comment by KrasnayaPloshchad** [comment] 2016-10-14 03:49
This is what I have seen on BabelPad
![default](https://cloud.githubusercontent.com/assets/10364351/19375173/09b28d24-9204-11e6-85ad-2d964abf8b27.PNG)

Then I copy the test from here and I produce an image with current version of hb.view.exe
`type test.txt | hb-view.exe C:\Windows\Fonts\Nirmala.ttf --output-format=png --output-file=image.png`
![image](https://cloud.githubusercontent.com/assets/10364351/19375195/46a735f4-9204-11e6-80d8-458d342762fb.png)

**Comment by MayuraVerma** [comment] 2016-10-14 12:21
@KrasnayaPloshchad can u do the same with Noto Sans and Serif Kannada. Is this a problem in harfbuzz or font?

Does babelpad use harfbuzz or directwrite?

**Comment by KrasnayaPloshchad** [comment] 2016-10-14 13:34
@MayuraVerma OK I can reproduce them with Noto Sans and Serif Kannada, it seems to me that this is caused by HarfBuzz.

Here is my test with BabelPad
![1](https://cloud.githubusercontent.com/assets/10364351/19388755/cfd58fc0-9253-11e6-86c9-c193a6142245.PNG)
![2](https://cloud.githubusercontent.com/assets/10364351/19388780/e1f5ab54-9253-11e6-8f56-7a2fd2c4612a.PNG)

Here is my test with hb-view
![image1](https://cloud.githubusercontent.com/assets/10364351/19389146/5a3bf356-9255-11e6-90b8-ed8817945b45.png)
![image2](https://cloud.githubusercontent.com/assets/10364351/19389161/62e33c12-9255-11e6-967b-b42d1cc8d317.png)

[BabelPad](http://www.babelstone.co.uk/Software/BabelPad.html) does not use HarfBuzz and DirectWrite, it relys on Uniscribe and ClearType. Both Chrome and Firefox use HarfBuzz for shaping, also can choose to use DW for glyph rendering.

**Comment by MayuraVerma** [comment] 2016-10-14 14:19
@KrasnayaPloshchad Thanks again. 
1. Where can I download this utility?
2. You demonstrated Noto Serif Kannada has futher issue with Harfbuzz as reported in #347 

@behdad Please review this.

**Comment by KrasnayaPloshchad** [comment] 2016-10-14 15:38
@MayuraVerma If you want to use this utility, you can go to HarfBuzz website, and then you can find the download link.

**Comment by behdad** [comment] 2016-10-24 09:45
I can confirm these.  Working on it.

**Comment by behdad** [comment] 2016-10-24 11:16
Ok.  This is an ugly one :(.  @jfkthame I need your help.

The problem is, in most other Indic scripts, a sequence of "ZWJ H C" is used force a subjoined form, whereas in Kannada, the way Tunga font is coded, a "H ZWJ C" is used to force a subjoined form.  The problem is, "H ZWJ" is also used to request an explicit half-form.  So when we see a sequence "C H ZWJ C", both of these cases can happen, and do happen with Tunga:

  - One possibility is that "C H C" would form subjoined, whereas adding ZWJ blocks it and we get half-form followed by base,

  - Other case is where "C H C" normally wouldn't form subjoined and ZWJ forces it and we get base followed by half-form.

Since the logic involves complex substitutions in the font including backtrack and lookahead, we cannot know this during initial base selection and have to run lookups to know which happens to be the case.  Sure, I can implement extra logic in final reordering to move base forward if we see ZWJ C following base.

However!  This is where it gets tricky: some of the right-matras in Kannada should be positioned before-sub.  Since we did the sort in initial reordering, they are now between previously decided base, and the later consonants that we want to pick as base.  Ouch!

It looks to me that MS Kannada shaper has an extra reordering logic that we have not seen in any other shaper.  Here's what I propose: we categorize all right-matras as after-sub.  Then in final reordering when adjust base, then go ahead and move those before any below consonants.  To do this however, we need a new positional category.  I'm not thrilled about that, but let me see what I can do.

**Comment by jfkthame** [comment] 2016-10-24 14:38
Hold on.... I'm not sure I understand the issue being reported here, or whether it's being correctly reported.

The reporter is using a sequence RA + Halant + ZWJ + KA (or other trailing consonant).

On Windows 10 (current Insider build), I can reproduce the desired ("correct"?) display (with subjoined KA) as shown in
 ![image](https://cloud.githubusercontent.com/assets/1706499/19648809/45e6b096-99fb-11e6-9ecf-465f9160506d.png)
in BabelPad, but I do NOT see this with MS Word; there, I see the same rendering (with half-forms + full KA) as the reported hb-view result. Maybe my Word is too old (from Office 2010)?

In general, though, I think the correct way to force a subjoined consonant is with ZWJ, Halant, C, and _not_ Halant, ZWJ, C as in the example here. This works for me in all contexts where I've tried it.

I also looked at the behavior of Apple's Kannada font (Kannada MN) on OS X; there, too, the sequence RA + ZWJ + Halant + KA renders as RA + subjoined-KA, while RA + Halant + ZWJ + KA renders as half-RA + KA.

In MS Edge, I do see RA + Halant + ZWJ + KA generating a subjoined KA (i.e. the result is indistinguishable from RA + ZWJ + Halant + KA), but that seems to be specific to RA. I'm guessing it's somehow related to Reph processing, as in the absence of any join-control, the RA + Halant here would form Reph, and the ZWJ suppresses that. But the fact that it then gives a subjoined KA seems to be a non-interoperable quirk, and I wonder if it's really intended/desired, or just an inadvertent quirk of the implementation.

So I'm suggesting that -- perhaps -- this is an incorrect encoded representation of the desired form. They should be using ZWJ + Halant + C for the subjoined consonant. The fact that the behavior of the mis-spelled sequence Halant + ZWJ + C is inconsistent between systems (when it follows RA) is bad, but it's not yet clear to me which result would be correct. (Time to go read TUS, I suppose...)

**Comment by roozbehp** [comment] 2016-10-24 19:40
The Unicode section on Kannada seems to confirm @jfkthame's analysis (I didn't go very deep). See http://www.unicode.org/versions/Unicode9.0.0/ch12.pdf, where is shows, in page 498:

U+0CB0 ರ _ra_ + ZWJ + U+0CCD ◌ ್ _halant_ + U+0C95 ಕ _ka_ → ರ‍್ಕ _rka_

As for how virama+ZWJ should be handled in various scripts, it's a pretty complex story, and I tend to forget the answers. But in short, virama+ZWJ tends to generate half-forms of the previous consonant (or consonant cluster), or in cases where the repha or a repha-like character may not be formed by default (like in Gurmukhi or repaya in Sinhala), form a repha over the second cosonant (or post-ra cluster).

/cc @cibu

**Comment by roozbehp** [comment] 2016-10-24 19:42
Of course compatibility with other platforms showing similar rendering is very important to Android, so we'd like this "bug" fixed. But the sequence may not be very frequent (since it can be said it's misencoded), so we can wait until the problem is well understood :)

**Comment by MayuraVerma** [comment] 2016-10-24 21:46
@roozbehp @behdad 
Now the wiki page looks fine after swapping "U+0ccdU+200d" to "U+200dU+0ccd"

Now, I wonder how MS word was able to render this text with incorrect sequence. 

So say the least harfbuzz renders the text with U+0CB0 ರ ra + ZWJ + U+0CCD ◌ ್ halant + U+0C95 ಕ ka → ರ‍್ಕ rka correctly.

**Comment by mjansche** [comment] 2016-10-24 22:43
In many scripts there is the potential for ambiguity in consonant clusters involving RA as the logical first component. The Standard treats Kannada like Bengali (but unlike Sinhala) in this regard: RA ZWJ VIRAMA C2 means the full form of RA is used (the ZWJ blocks the interpretation as REPHA) together with a ligated form of C2.

There is often a problem on the input side; e.g. Bengali input methods may not make it easy to input RA ZWJ VIRAMA YA when needed. I'm wondering if there is a similar issue with inputting RA-clusters in Kannada.

**Comment by MayuraVerma** [comment] 2016-10-25 00:55
Here is another example of usage of "U+0ccdU+200d".

I am not sure if this is legal combination at all!

check ರ್‍ಯಾಲಿಗಳ in the below article
http://www.prajavani.net/news/article/2016/10/25/447516.html

**Comment by behdad** [comment] 2016-10-26 07:03
Thanks @jfkthame for the analysis.  I have had totally missed that the initial consonant is Ra.  So, looks like this is similar to Bengali Ra H ZWJ Ya.  Let me give it a try again.

**Comment by KrasnayaPloshchad** [comment] 2016-10-29 10:01
@behdad This is known as “canonically equivalent”, I think this should be always treated as standard sequence.

**Comment by lianghai** [comment] 2016-12-09 14:56
- Sequence `<consonant virama ZWJ consonant>` is undefined for Kannada (since it doesn't have any C1 form, and it has repha by default).
- The desired structure (repha prevented) should be requested by <RA ZWJ virama consonant>. Yes, it's very similar to Bangla's case.
- Tunga has messy, non-standard OTL rules. Nirmala UI isn't backward-compatible to Tunga in terms of this behavior.
- Please do not refer to Apple's MN fonts. Those fonts are not OpenType ones, and they have extremely buggy shaping behaviors.

**Comment by KrasnayaPloshchad** [comment] 2017-02-02 09:57
> Both Chrome and Firefox use HarfBuzz for shaping, also can choose to use DW for glyph rendering.

LibreOffice is also rewrite the text layout engine based on HarfBuzz in version 5.3, this version will coming after several days.

**Comment by KrasnayaPloshchad** [comment] 2017-02-02 19:04
> LibreOffice is also rewrite the text layout engine based on HarfBuzz in version 5.3, this version will coming after several days.

It’s coming.

**Comment by behdad** [comment] 2017-07-14 13:43
Ok, so looks like there's no bug with valid text.  However, we still want to test latest Windows and try to understand what it does and try to match.

**Comment by behdad** [comment] 2017-07-14 13:44
Closing in favor of https://github.com/behdad/harfbuzz/issues/435 which doesn't take 15 minutes to read.

**Closed by behdad** 2017-07-14 13:44 UTC
Labels: Android, enhancement
